---
R1:
    hostname: '10.10.20.171'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'
    group:
      - cisco_router 
    connection_options:
        netmiko:
          extras:
            secret: 'cisco'
            session_log: logs/R1.log

R2:
    hostname: '10.10.20.172'
    port: 22
    username: 'cisco'
    password: 'cisco'
    platform: 'cisco_ios'
    group:
      - cisco_router
    connection_options:
        netmiko:
          extras:
            secret: 'cisco'
            session_log: logs/R2.log
